spring:
  datasource:
    url: ${DB_HOST:jdbc:mysql://localhost:3306/order-db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:fiap}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

  application:
    name: ORDER-SERVICE

server:
  port: 8082

mapstruct:
  defaultComponentModel=spring:

  # FEIGN PRODUCT

feign:
  client:
    config:
      product:
        url: ${HOST_PRODUCT_SERVICE:http://localhost:8080/product}
      payment:
        url: ${HOST_PAYMENT:http://localhost:8080/payment}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
